version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}

  server:
    build: ./server/app
    volumes:
      - ./server/app:/server
    environment:
      - DB_USER=${POSTGRES_USER:?err}
      - DB_HOST=${POSTGRES_HOST:?err}
      - DB_PASSWORD=${POSTGRES_PASSWORD:?err}
      - DB_PORT=${POSTGRES_PORT}
      - DB_DATABASE=${POSTGRES_DB:?err}
    ports:
      - '80:80'
    depends_on:
      - db
    command: sh -c "sh prestart.sh && uvicorn app.main:app --reload --host 0.0.0.0 --port 80 --reload"

  client:
    build:
      context: .
      dockerfile: dockerfiles/client.dockerfile

    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      server:
        condition: service_started
