"""add relation ship teacher course

Revision ID: 5ca593e4703c
Revises: 873dc0c8fcaa
Create Date: 2023-04-28 04:04:21.629615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5ca593e4703c"
down_revision = "873dc0c8fcaa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("teacher_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_course_teacher",
        "courses",
        "users",
        ["teacher_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_course_teacher", "courses", type_="foreignkey")
    op.drop_column("courses", "teacher_id")
    # ### end Alembic commands ###
