"""Add unique constraint to student_course table

Revision ID: 873dc0c8fcaa
Revises: e1d492878773
Create Date: 2023-04-28 02:48:53.811328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "873dc0c8fcaa"
down_revision = "e1d492878773"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_student_course", "student_course", ["student_id", "course_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_student_course", "student_course", type_="unique")
    # ### end Alembic commands ###
