"""add course table

Revision ID: ca208aec097f
Revises: 78cb112020e9
Create Date: 2023-04-27 20:54:19.680521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca208aec097f"
down_revision = "78cb112020e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("startDate", sa.Date(), nullable=False),
        sa.Column("endDate", sa.Date(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.alter_column("event", "end", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index("ix_user_id", table_name="user")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.alter_column("event", "end", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("courses")
    # ### end Alembic commands ###
